### ISSUE TITLE
When using 3d mode you lose 8-bit transparency

### ISSUE THREAD

**Issue by fu-raz** [joshmarinacci/aminogfx-gl#9]
I've been experimenting with 3d mode. Whenever I use a PNG file with an 8-bit alpha channel (so a 32 bit png) I lose some of the transparency. Only the fully transparent pixels remain transparent.

Result:
![amino-render-3d](https://user-images.githubusercontent.com/5355154/26978592-5bed15a8-4d2c-11e7-81a0-e2be9d8bea86.png)

Expectation:
![amino-render-2d](https://user-images.githubusercontent.com/5355154/26978607-67fe1a86-4d2c-11e7-8b82-3a668da1b0a8.png)

I've made a simple repository with some of my tests (https://github.com/fu-raz/amino-performance-tests). Nothing fancy, just a few simple tests that show different ways to accomplish the same thing. I run these tests on a raspberry Pi3 (overclocked just a tad). If you compare the 'layers-render-3d.js' to the 'layers-render-timeout-visibility.js', you can see what I mean. The 3d one performs a lot better, except for the transparency.

Is this done for performance reasons? Or is this something we can fix?

**Comment by cbratschi** [comment]
This is the expected behavior. OpenGL uses a z-buffer which means only one pixel gets stored in the buffer and is rendered afterwards. As a special feature we support fully transparent pixels which means those pixels are not visible at all.

What you can do is separate different layers. If you need 8-bit alpha use non-3D mode.

**Comment by fu-raz** [comment]
I was afraid of this. Makes sense. Thanks for the lightning fast response.
